const JOURNAL_CATEGORIES = [
  { id: 'life-sciences',     name: 'Life Sciences',              icon: 'dna' },
  { id: 'medicine',          name: 'Medicine & Health',          icon: 'heart-pulse' },
  { id: 'physical-sciences', name: 'Physical Sciences',          icon: 'atom' },
  { id: 'engineering',       name: 'Engineering & Technology',   icon: 'cpu' },
  { id: 'social-sciences',   name: 'Social Sciences',            icon: 'people' },
  { id: 'humanities',        name: 'Humanities',                 icon: 'book' },
  { id: 'psychology',        name: 'Psychology',                 icon: 'brain' },
  { id: 'computer-science',  name: 'Computer Science',           icon: 'code-slash' },
  { id: 'interdisciplinary', name: 'Interdisciplinary',          icon: 'diagram-3' },
  { id: 'open-access',       name: 'Open Access',                icon: 'unlock' },
];

const REFERENCE_STYLES = {
  nature:    { name: 'Nature Style',        example: '1. Smith, J. et al. Nature 592, 41–47 (2021).' },
  vancouver: { name: 'Vancouver / NLM',     example: 'Smith J, Jones A. Article title. J Med. 2021;45(2):12-8.' },
  apa7:      { name: 'APA 7th Edition',     example: 'Smith, J. A., & Jones, B. C. (2021). Title. Journal, 45(2), 12–18.' },
  chicago:   { name: 'Chicago (Notes)',     example: 'Smith, John. "Title." Journal 45, no. 2 (2021): 12–18.' },
  mla9:      { name: 'MLA 9th Edition',     example: 'Smith, John, et al. "Article Title." Journal, vol. 45, no. 2, 2021, pp. 12–18.' },
  ieee:      { name: 'IEEE',                example: '[1] J. Smith and A. Jones, "Title," IEEE Trans., vol. 45, no. 2, pp. 12–18, 2021.' },
  acs:       { name: 'ACS Style',           example: 'Smith, J.; Jones, A. J. Am. Chem. Soc. 2021, 143, 1234–1240.' },
  ama:       { name: 'AMA Style',           example: 'Smith J, Jones A. Article title. JAMA. 2021;325(2):123-130. doi:xxx' },
};

const JOURNALS = [
  // ─── LIFE SCIENCES ──────────────────────────────────────────────────────────
  {
    id: 'nature',
    name: 'Nature',
    publisher: 'Springer Nature',
    category: 'life-sciences',
    impactFactor: 69.5,
    tier: 'elite',
    issn: '0028-0836',
    openAccess: false,
    description: 'One of the world\'s most prestigious multidisciplinary journals, publishing research of outstanding scientific importance across all fields.',
    wordLimit: 3000,
    abstractLimit: 150,
    referenceStyle: 'nature',
    maxReferences: 30,
    maxFigures: 8,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
    submissionGuidelines: [
      'Findings must be of broad scientific significance across disciplines',
      'Introduction: brief 2–3 paragraphs, no subheadings, ends with a summary of results',
      'Results and Discussion may be combined; Methods appear after Discussion',
      'Extended Data allowed (up to 10 items) for supporting figures/tables',
      'Supplementary Information for datasets, code, and extended protocols',
      'Statistical reporting must follow Nature Research Reporting Summary',
      'Data availability and code availability statements are mandatory',
      'All authors must complete a competing interests declaration',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Max 90 characters; avoid abbreviations and jargon' },
      { section: 'Abstract',               notes: '150 words max; unstructured; last sentence = main conclusion' },
      { section: 'Introduction',           notes: '200–500 words; 2–3 paragraphs; no subheadings' },
      { section: 'Results',                notes: 'Subheadings allowed; present data without discussion' },
      { section: 'Discussion',             notes: 'Interpret findings; relate to existing literature' },
      { section: 'Methods',                notes: 'Placed after Discussion; use Online Methods for detail' },
      { section: 'Data Availability',      notes: 'Mandatory statement' },
      { section: 'Code Availability',      notes: 'Required if code was used' },
      { section: 'References',             notes: 'Nature format; numbered; max 30' },
      { section: 'Acknowledgements',       notes: 'Funding, contributions of non-authors' },
      { section: 'Author Contributions',   notes: 'Required; use CRediT taxonomy' },
      { section: 'Competing Interests',    notes: 'Required declaration from all authors' },
    ],
    thesisConversionTips: [
      'Eliminate standalone Literature Review; compress to 2–3 key background paragraphs in Introduction',
      'Select only 1–2 most significant findings from the thesis',
      'Remove all thesis-specific framing ("In this thesis...", "Chapter 2 showed...")',
      'Reduce reference list to ≤30 most essential citations',
      'Condense Methods; move detailed protocols to Online Methods',
      'Ensure your findings have cross-disciplinary significance — Nature rejects narrow-scope work',
      'Add a "broader impact" sentence at the end of the Discussion',
    ],
  },
  {
    id: 'science',
    name: 'Science',
    publisher: 'AAAS',
    category: 'life-sciences',
    impactFactor: 56.9,
    tier: 'elite',
    issn: '0036-8075',
    openAccess: false,
    description: 'The flagship journal of AAAS, publishing cutting-edge research across all scientific disciplines with major societal implications.',
    wordLimit: 4500,
    abstractLimit: 125,
    referenceStyle: 'science',
    maxReferences: 40,
    maxFigures: 5,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Results', 'Discussion', 'Materials and Methods'],
    submissionGuidelines: [
      'Findings must represent a major advance in the field with broad significance',
      'One-paragraph abstract, max 125 words; no citations in abstract',
      'Introduction is one paragraph (200 words max)',
      'Figures should each advance the narrative; avoid redundant panels',
      'Supplementary Materials can include methods, data, and additional figures',
      'ORCID iDs required for all authors',
      'Structured Materials and Methods placed at end or in Supplementary',
    ],
    manuscriptStructure: [
      { section: 'Title',                       notes: 'Concise; max 100 characters recommended' },
      { section: 'Abstract',                    notes: 'One paragraph; 125 words max; no references' },
      { section: 'Introduction',                notes: 'One paragraph; 150–200 words; end with hypothesis/aim' },
      { section: 'Results',                     notes: 'Subheadings encouraged; data-forward narrative' },
      { section: 'Discussion',                  notes: 'Broader context and limitations' },
      { section: 'Materials and Methods',       notes: 'At end or in Supplementary; detailed protocols' },
      { section: 'Supplementary Materials',     notes: 'Additional figures, tables, data' },
      { section: 'References',                  notes: 'Science format; numbered; up to 40' },
      { section: 'Acknowledgments',             notes: 'Funding, contributor roles' },
    ],
    thesisConversionTips: [
      'Compress Literature Review to a single introductory paragraph',
      'Identify the ONE most novel, high-impact finding to anchor the manuscript',
      'Trim Methods to essentials; move exhaustive detail to Supplementary',
      'Reframe findings for broad scientific audience, not just field specialists',
      'Science favors clean, story-driven narratives — reorganize if needed',
    ],
  },
  {
    id: 'cell',
    name: 'Cell',
    publisher: 'Cell Press / Elsevier',
    category: 'life-sciences',
    impactFactor: 66.9,
    tier: 'elite',
    issn: '0092-8674',
    openAccess: false,
    description: 'Premier journal in molecular and cell biology, publishing transformative research in genetics, genomics, structural biology, and systems biology.',
    wordLimit: 8000,
    abstractLimit: 150,
    referenceStyle: 'cell',
    maxReferences: 60,
    maxFigures: 7,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '6–10',
    sections: ['Introduction', 'Results', 'Discussion', 'STAR Methods'],
    submissionGuidelines: [
      'STAR Methods format required (Structured, Transparent, Accessible Reporting)',
      'Key Resources Table required in STAR Methods (reagents, tools, datasets)',
      'Graphical Abstract required: one-panel figure summarizing the study',
      'Highlights required: 3–4 bullet points (max 85 characters each)',
      'Supplemental Information submitted as separate file',
      'All raw data and code must be deposited in public repositories',
      'Author contributions using CRediT taxonomy required',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Informative and concise' },
      { section: 'Graphical Abstract',     notes: 'Required: one-panel visual summary' },
      { section: 'Highlights',             notes: '3–4 bullet points, max 85 characters each' },
      { section: 'Abstract',               notes: '150 words max; unstructured' },
      { section: 'Keywords',               notes: '6–10 keywords' },
      { section: 'Introduction',           notes: 'Background and study rationale; 3–5 paragraphs' },
      { section: 'Results',                notes: 'Subheadings; each corresponding to a figure' },
      { section: 'Discussion',             notes: 'Implications and limitations' },
      { section: 'STAR Methods',           notes: 'Structured methods with Key Resources Table' },
      { section: 'Supplemental Information', notes: 'Additional data and figures' },
      { section: 'References',             notes: 'Cell format; max ~60' },
      { section: 'Author Contributions',   notes: 'CRediT taxonomy required' },
    ],
    thesisConversionTips: [
      'Create a Graphical Abstract — essential and reviewed critically at Cell',
      'Write 3–4 Highlights bullets that capture your key findings',
      'Reformat Methods as STAR Methods with the required Key Resources Table',
      'Restructure Results so each subheading maps to a specific figure',
      'Deposit all raw data in a public repository (GEO, Zenodo, Dryad)',
      'Cell values mechanistic depth — ensure your thesis results chapter conveys mechanism',
    ],
  },
  {
    id: 'elife',
    name: 'eLife',
    publisher: 'eLife Sciences Publications',
    category: 'life-sciences',
    impactFactor: 8.7,
    tier: 'high',
    issn: '2050-084X',
    openAccess: true,
    description: 'Open-access journal for exceptional advances in life sciences and biomedicine, known for constructive peer review and research transparency.',
    wordLimit: null,
    abstractLimit: 150,
    referenceStyle: 'nature',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'structured',
    abstractSections: ['Background', 'Results', 'Conclusions and Relevance'],
    keywordsRequired: true,
    keywordsCount: '6 or fewer',
    sections: ['Introduction', 'Results', 'Discussion', 'Materials and Methods'],
    submissionGuidelines: [
      'No word or figure limits — completeness valued over brevity',
      'eLife Digest (lay summary) strongly encouraged',
      'Registered Reports and Replication Studies welcomed',
      'Open peer review; reviewer identities may be published',
      'Impact Statement required: 1–2 sentences on significance',
      'All data and code must be publicly available',
      'Preprint posting encouraged before submission',
    ],
    manuscriptStructure: [
      { section: 'Title',               notes: 'Descriptive; can be longer than other journals' },
      { section: 'Abstract',            notes: 'Structured: Background, Results, Conclusions; ~150 words' },
      { section: 'Impact Statement',    notes: '1–2 sentences; required' },
      { section: 'Keywords',            notes: 'Up to 6' },
      { section: 'Introduction',        notes: 'Full background; place in context of field' },
      { section: 'Results',             notes: 'Complete data presentation' },
      { section: 'Discussion',          notes: 'Thorough interpretation; limitations' },
      { section: 'Materials and Methods', notes: 'Full detail; can be at end or after Introduction' },
      { section: 'eLife Digest',        notes: 'Optional lay summary; ~300–500 words' },
      { section: 'References',          notes: 'No limit; author-date or numbered format' },
    ],
    thesisConversionTips: [
      'eLife is ideal for thesis conversion — no length limits allow full thesis depth',
      'Write a structured abstract with Background/Results/Conclusions sections',
      'Write an eLife Digest — a 300-word lay summary accessible to non-specialists',
      'Include complete Methods rather than summarizing; reproducibility is key',
      'Post as a preprint (bioRxiv) before or alongside submission',
      'Your thorough Literature Review can be condensed but need not be eliminated',
    ],
  },
  {
    id: 'current-biology',
    name: 'Current Biology',
    publisher: 'Cell Press / Elsevier',
    category: 'life-sciences',
    impactFactor: 12.9,
    tier: 'high',
    issn: '0960-9822',
    openAccess: false,
    description: 'Broad-scope biology journal covering cell biology, genetics, neuroscience, ecology, evolution, and behavior.',
    wordLimit: 5000,
    abstractLimit: 150,
    referenceStyle: 'cell',
    maxReferences: 50,
    maxFigures: 6,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '6–10',
    sections: ['Introduction', 'Results', 'Discussion', 'STAR Methods'],
    submissionGuidelines: [
      'STAR Methods format required',
      'Graphical Abstract required for Research Articles',
      'Short Reports (2,000 words) available for focused findings',
      'Highlights required (3–4 bullets)',
      'Must demonstrate significance beyond the specialist field',
    ],
    manuscriptStructure: [
      { section: 'Title',               notes: 'Concise; informative' },
      { section: 'Graphical Abstract',  notes: 'Required for Research Articles' },
      { section: 'Highlights',          notes: '3–4 bullets, 85 chars max each' },
      { section: 'Abstract',            notes: '150 words max' },
      { section: 'Keywords',            notes: '6–10' },
      { section: 'Introduction',        notes: '3–5 paragraphs; establish significance' },
      { section: 'Results',             notes: 'Figure-linked subheadings' },
      { section: 'Discussion',          notes: '2–4 paragraphs; broader implications' },
      { section: 'STAR Methods',        notes: 'Key Resources Table + structured methods' },
      { section: 'References',          notes: 'Cell style; ~50 max' },
    ],
    thesisConversionTips: [
      'Use STAR Methods format — restructure Methods chapter accordingly',
      'Frame results to appeal beyond your narrow specialty',
      'Consider submitting single compelling chapter as a Short Report',
    ],
  },

  // ─── MEDICINE ────────────────────────────────────────────────────────────────
  {
    id: 'nejm',
    name: 'New England Journal of Medicine',
    shortName: 'NEJM',
    publisher: 'Massachusetts Medical Society',
    category: 'medicine',
    impactFactor: 176.1,
    tier: 'elite',
    issn: '0028-4793',
    openAccess: false,
    description: 'The world\'s most widely read and influential medical journal, publishing original clinical research and reviews of major significance.',
    wordLimit: 3400,
    abstractLimit: 250,
    referenceStyle: 'vancouver',
    maxReferences: 70,
    maxFigures: 5,
    maxTables: 4,
    abstractStructure: 'structured',
    abstractSections: ['Background', 'Methods', 'Results', 'Conclusions'],
    keywordsRequired: false,
    sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'ICMJE authorship criteria must be satisfied by all listed authors',
      'CONSORT/STROBE/PRISMA reporting standards required',
      'Clinical trial registration number required in abstract',
      'Structured abstract: Background, Methods, Results, Conclusions (250 words)',
      'Trial protocol and statistical analysis plan must be available on request',
      'IRB/Ethics approval documentation required',
      'EQUATOR Network reporting guidelines apply',
      'All affiliations, conflicts, and funding sources must be disclosed',
    ],
    manuscriptStructure: [
      { section: 'Title',             notes: 'Specific; max 100 characters' },
      { section: 'Abstract',         notes: 'Structured; 250 words max; 4 headers' },
      { section: 'Introduction',     notes: 'Brief; 1–2 paragraphs; clinical context and study aim' },
      { section: 'Methods',          notes: 'Study design, population, outcomes, statistics' },
      { section: 'Results',          notes: 'Flow diagram for trials; primary then secondary outcomes' },
      { section: 'Discussion',       notes: 'Findings, limitations, generalizability, clinical implications' },
      { section: 'References',       notes: 'Vancouver; numbered; up to 70' },
      { section: 'Disclosures',      notes: 'Financial and non-financial conflicts of interest' },
      { section: 'Acknowledgments',  notes: 'Funding; non-author contributions' },
    ],
    thesisConversionTips: [
      'Medical theses must become clinical research articles — apply CONSORT/STROBE/PRISMA',
      'Write a structured abstract with all 4 required sections',
      'Introduction must be ≤2 paragraphs focused on clinical problem and study gap',
      'Methods must include ethics approval statement and registration number',
      'NEJM expects statistically rigorous results with appropriate confidence intervals',
      'Focus on one primary outcome; present secondary outcomes briefly',
      'Discuss clinical implications explicitly — NEJM readers are clinicians',
    ],
  },
  {
    id: 'lancet',
    name: 'The Lancet',
    publisher: 'Elsevier',
    category: 'medicine',
    impactFactor: 168.9,
    tier: 'elite',
    issn: '0140-6736',
    openAccess: false,
    description: 'Premier international medical journal covering clinical medicine, public health, and global health, with significant policy influence.',
    wordLimit: 4000,
    abstractLimit: 250,
    referenceStyle: 'vancouver',
    maxReferences: 60,
    maxFigures: 5,
    maxTables: 4,
    abstractStructure: 'structured',
    abstractSections: ['Background', 'Methods', 'Findings', 'Interpretation', 'Funding'],
    keywordsRequired: false,
    sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'Globally relevant findings preferred; considers health equity implications',
      'Abstract uses "Findings" not "Results" and requires a Funding statement',
      'Panel summary required: 50-word plain language summary',
      'Reporting guideline compliance (CONSORT, STROBE, etc.) mandatory',
      'The Lancet uses "Correspondence" and "Comment" for shorter contributions',
      'Open data sharing policy applies',
    ],
    manuscriptStructure: [
      { section: 'Title',          notes: 'Informative; max 120 characters' },
      { section: 'Abstract',       notes: 'Structured; 5 sections including Funding' },
      { section: 'Introduction',   notes: '3–4 paragraphs; global context preferred' },
      { section: 'Methods',        notes: 'Full detail; ethics, population, outcomes' },
      { section: 'Results',        notes: 'Primary finding prominently placed' },
      { section: 'Discussion',     notes: 'Policy and global health implications' },
      { section: 'Panel',          notes: '50-word summary panel; required' },
      { section: 'References',     notes: 'Vancouver format; ~60 max' },
      { section: 'Contributors',   notes: 'Author roles explicitly stated' },
      { section: 'Declaration of Interests', notes: 'Required' },
      { section: 'Data Sharing',   notes: 'Required statement' },
    ],
    thesisConversionTips: [
      'Lancet favors global health impact — frame local findings in global context',
      'Abstract requires a "Funding" section even if stating "no external funding"',
      'Include a policy implication statement in Discussion',
      'Write a 50-word plain language "Panel" summary',
      'Health equity angle strengthens Lancet submissions',
    ],
  },
  {
    id: 'jama',
    name: 'JAMA',
    shortName: 'JAMA',
    publisher: 'American Medical Association',
    category: 'medicine',
    impactFactor: 157.3,
    tier: 'elite',
    issn: '0098-7484',
    openAccess: false,
    description: 'Journal of the American Medical Association — publishes original research, reviews, and clinical guidelines of direct relevance to physicians.',
    wordLimit: 3000,
    abstractLimit: 300,
    referenceStyle: 'ama',
    maxReferences: 60,
    maxFigures: 5,
    maxTables: 5,
    abstractStructure: 'structured',
    abstractSections: ['Importance', 'Objective', 'Design Setting and Participants', 'Exposures', 'Main Outcomes and Measures', 'Results', 'Conclusions and Relevance'],
    keywordsRequired: false,
    sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'JAMA Network journals share guidelines; check specific journal scope',
      'Abstract has 7 structured sections for clinical research',
      '"Importance" section replaces traditional background/context',
      'CONSORT diagram mandatory for RCTs; STROBE for observational studies',
      'All primary and secondary outcomes pre-specified and registered',
      'AMA citation style required',
      'Conflict of interest disclosure within past 36 months required',
    ],
    manuscriptStructure: [
      { section: 'Title',                    notes: 'PICO format preferred for trials' },
      { section: 'Abstract',                 notes: 'Structured; 7 sections; 300 words max' },
      { section: 'Introduction',             notes: '2–3 short paragraphs; clinical relevance' },
      { section: 'Methods',                  notes: 'Study design, setting, participants, interventions, outcomes, analysis' },
      { section: 'Results',                  notes: 'Tables and figures; primary outcome first' },
      { section: 'Discussion',               notes: 'Clinical implications; study strengths and limitations' },
      { section: 'References',               notes: 'AMA style; numbered; ~60' },
      { section: 'Conflict of Interest Disclosures', notes: 'Required; 36-month lookback' },
      { section: 'Funding/Support',          notes: 'Required' },
    ],
    thesisConversionTips: [
      'Replace "Background" with "Importance" in abstract — JAMA\'s distinctive requirement',
      'JAMA\'s 7-section structured abstract is unique; adapt carefully',
      'Focus on clinical relevance and patient outcomes above mechanistic detail',
      'Apply AMA citation style throughout',
      'Ensure all outcomes were pre-registered; JAMA is strict on this',
    ],
  },
  {
    id: 'bmj',
    name: 'The BMJ',
    publisher: 'BMJ Publishing Group',
    category: 'medicine',
    impactFactor: 105.7,
    tier: 'elite',
    issn: '0959-8138',
    openAccess: false,
    description: 'British Medical Journal — one of the world\'s oldest general medical journals, known for strong focus on research methodology and clinical practice.',
    wordLimit: 3500,
    abstractLimit: 250,
    referenceStyle: 'vancouver',
    maxReferences: 50,
    maxFigures: 5,
    maxTables: 4,
    abstractStructure: 'structured',
    abstractSections: ['Objectives', 'Design', 'Setting', 'Participants', 'Interventions', 'Main Outcome Measures', 'Results', 'Conclusions'],
    keywordsRequired: false,
    sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'What is already known / What this study adds box required (3 bullets each)',
      'ICMJE reporting standards; EQUATOR guidelines apply',
      'Open data sharing strongly encouraged',
      'Patient involvement statement required where applicable',
      'Open Peer Review — reviewer names published with permission',
      'Rapid Responses available for post-publication discussion',
    ],
    manuscriptStructure: [
      { section: 'Title',              notes: 'Informative, specific' },
      { section: '"What is known / What this adds"', notes: '3+3 bullet box; required' },
      { section: 'Abstract',           notes: 'Structured; 8 sections; 250 words' },
      { section: 'Introduction',       notes: 'Brief; study rationale' },
      { section: 'Methods',            notes: 'Full reporting; patient involvement' },
      { section: 'Results',            notes: 'CONSORT or STROBE compliant' },
      { section: 'Discussion',         notes: 'Limitations; strengths; policy implications' },
      { section: 'References',         notes: 'Vancouver; ~50' },
      { section: 'Transparency Statement', notes: 'Required' },
    ],
    thesisConversionTips: [
      'Write the "What this study adds" box (3 brief bullets) — unique BMJ requirement',
      'Patient and public involvement (PPI) statement is highly valued at BMJ',
      'BMJ\'s 8-section abstract is the most detailed; plan carefully',
      'BMJ favors pragmatic trials and policy-relevant findings',
    ],
  },
  {
    id: 'plos-medicine',
    name: 'PLOS Medicine',
    publisher: 'PLOS',
    category: 'medicine',
    impactFactor: 15.8,
    tier: 'high',
    issn: '1549-1676',
    openAccess: true,
    description: 'Open-access journal publishing research that advances medical understanding and directly affects clinical practice or health policy.',
    wordLimit: 4000,
    abstractLimit: 300,
    referenceStyle: 'vancouver',
    maxReferences: null,
    maxFigures: 15,
    maxTables: 15,
    abstractStructure: 'structured',
    abstractSections: ['Background', 'Methods and Findings', 'Conclusions'],
    keywordsRequired: false,
    sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'All data must be publicly available; no exceptions',
      'Trial registration required for all clinical trials',
      'Minimum dataset for all studies must be deposited',
      'EQUATOR reporting guidelines mandatory',
      'APC (Article Processing Charge) required for open access',
      'Author Summary (150–200 words) in plain language required',
    ],
    manuscriptStructure: [
      { section: 'Title',             notes: 'Informative; avoid jargon' },
      { section: 'Abstract',         notes: 'Structured; 3 sections; 300 words max' },
      { section: 'Author Summary',   notes: '150–200 words; non-specialist audience; required' },
      { section: 'Introduction',     notes: 'Background; rationale; aims' },
      { section: 'Methods',          notes: 'Full reproducible detail; ethics statement' },
      { section: 'Results',          notes: 'Complete data; EQUATOR compliant' },
      { section: 'Discussion',       notes: 'Strengths; limitations; policy implications' },
      { section: 'References',       notes: 'No limit; Vancouver style' },
      { section: 'Data Availability Statement', notes: 'Required; specific repository links' },
    ],
    thesisConversionTips: [
      'PLOS Medicine requires an Author Summary — a key addition from any thesis',
      'Open data is non-negotiable: ensure your thesis data can be publicly shared',
      'Full methods can be included — no length limits hinder thesis conversion',
    ],
  },

  // ─── PHYSICAL SCIENCES ───────────────────────────────────────────────────────
  {
    id: 'prl',
    name: 'Physical Review Letters',
    shortName: 'PRL',
    publisher: 'American Physical Society',
    category: 'physical-sciences',
    impactFactor: 9.2,
    tier: 'elite',
    issn: '0031-9007',
    openAccess: false,
    description: 'The world\'s foremost physics letter journal, publishing short, high-impact papers across all subfields of physics.',
    wordLimit: 3500,
    abstractLimit: 600,
    referenceStyle: 'prl',
    maxReferences: 40,
    maxFigures: 4,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['(No formal sections — continuous narrative)'],
    submissionGuidelines: [
      'Letters format: concise (3,500 words equivalent) with no formal section headings',
      'Abstract: one paragraph, ≤600 characters (not words)',
      'Must establish novelty and broad physical significance',
      'Supplemental Material allowed but paper must be self-contained',
      'REVTeX or LaTeX strongly preferred; Word accepted',
      'Physical Review style for equations, units (SI), and references',
      'All figures must be publication quality (min 600 dpi)',
    ],
    manuscriptStructure: [
      { section: 'Title',               notes: 'Concise; specific to finding' },
      { section: 'Abstract',            notes: 'Max 600 characters; unstructured' },
      { section: 'Body Text',           notes: 'No formal headings; continuous; ~3,500 words' },
      { section: 'Acknowledgments',     notes: 'Funding agencies; collaboration credits' },
      { section: 'References',          notes: 'PRL style; numbered; ~40 max' },
      { section: 'Supplemental Material', notes: 'Optional; derivations, additional data' },
    ],
    thesisConversionTips: [
      'PRL requires continuous prose, not sectioned chapters — significant restructuring needed',
      'Extract one clean, surprising result from your thesis chapter',
      'The entire manuscript must fit ~3,500 word equivalents (abstract + body + references)',
      'Detailed derivations go in Supplemental Material',
      'Establish why your result is broadly relevant beyond your subfield',
      'Write using LaTeX/REVTeX for proper formatting',
    ],
  },
  {
    id: 'angewandte',
    name: 'Angewandte Chemie International Edition',
    shortName: 'Angew. Chem.',
    publisher: 'Wiley-VCH / GDCh',
    category: 'physical-sciences',
    impactFactor: 16.6,
    tier: 'elite',
    issn: '1433-7851',
    openAccess: false,
    description: 'Germany\'s premier chemistry journal, publishing outstanding research in all areas of chemistry including synthesis, catalysis, and materials.',
    wordLimit: 5000,
    abstractLimit: 250,
    referenceStyle: 'acs',
    maxReferences: 40,
    maxFigures: 8,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '5',
    sections: ['Introduction', 'Results and Discussion', 'Conclusion', 'Experimental Section'],
    submissionGuidelines: [
      'Communications (max 5 pages) and Full Papers (unlimited) accepted',
      'TOC (Table of Contents) graphic required: 3.5 × 9 cm, 150–300 dpi',
      '5 Keywords required',
      'Experimental section must include all synthetic procedures and characterization data',
      'Crystal structures must be deposited in CCDC before submission',
      'NMR, mass spectra, and analytical data in Supporting Information',
      'German language parallel title encouraged',
    ],
    manuscriptStructure: [
      { section: 'Title',                 notes: 'Chemical focus; with bold keywords possible' },
      { section: 'TOC Graphic',           notes: 'Required; 3.5 × 9 cm visual summary' },
      { section: 'Abstract',             notes: '250 words; unstructured; no citations' },
      { section: 'Keywords',             notes: 'Exactly 5' },
      { section: 'Introduction',         notes: 'Chemical context; prior art; aim' },
      { section: 'Results and Discussion', notes: 'Merged; figure/scheme-driven narrative' },
      { section: 'Conclusion',           notes: 'Brief; 1–2 paragraphs' },
      { section: 'Experimental Section', notes: 'Full detail; all compounds characterized' },
      { section: 'Supporting Information', notes: 'Spectra, crystallographic data, computational details' },
      { section: 'References',           notes: 'ACS style; ~40' },
    ],
    thesisConversionTips: [
      'Merge Results and Discussion into a single combined section (Angew. Chem. standard)',
      'Create a TOC graphic — essential; 3.5 × 9 cm horizontal visual',
      'Extract exactly 5 keywords; choose carefully for discoverability',
      'Move full spectra, crystallographic data, and analytical tables to Supporting Information',
      'Deposit crystal structures in CCDC before submission',
    ],
  },
  {
    id: 'acs-nano',
    name: 'ACS Nano',
    publisher: 'American Chemical Society',
    category: 'physical-sciences',
    impactFactor: 18.0,
    tier: 'high',
    issn: '1936-0851',
    openAccess: false,
    description: 'Premier journal covering all aspects of nanoscience and nanotechnology, from synthesis and characterization to devices and applications.',
    wordLimit: 10000,
    abstractLimit: 200,
    referenceStyle: 'acs',
    maxReferences: 60,
    maxFigures: 10,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '6',
    sections: ['Introduction', 'Results and Discussion', 'Conclusions', 'Methods'],
    submissionGuidelines: [
      'Articles, Communications, Reviews, and Perspectives accepted',
      'TOC graphic required for all articles',
      'Supporting Information for extensive data and methods',
      'Characterization data must be comprehensive (XRD, TEM, XPS, etc.)',
      'ACS ethical guidelines apply; no figure manipulation',
      'Authors must confirm experimental reproducibility',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Informative nanoscience terminology' },
      { section: 'TOC Graphic',            notes: 'Required; visual abstract' },
      { section: 'Abstract',              notes: '200 words; clear findings' },
      { section: 'Keywords',              notes: '6 terms' },
      { section: 'Introduction',          notes: 'State of nanoscience context; significance' },
      { section: 'Results and Discussion', notes: 'Combined; characterization + interpretation' },
      { section: 'Conclusions',           notes: 'Brief; key takeaways and outlook' },
      { section: 'Methods',              notes: 'After Conclusions; detailed synthesis and characterization' },
      { section: 'Supporting Information', notes: 'Extensive characterization data' },
      { section: 'References',            notes: 'ACS style; ~60' },
    ],
    thesisConversionTips: [
      'ACS Nano allows up to 10,000 words — full thesis chapters can convert with manageable editing',
      'Combine Results and Discussion sections',
      'Create a TOC graphic highlighting the nanomaterial or device concept',
      'Ensure comprehensive characterization is present or in Supporting Information',
    ],
  },

  // ─── ENGINEERING & TECHNOLOGY ────────────────────────────────────────────────
  {
    id: 'ieee-tpami',
    name: 'IEEE Transactions on Pattern Analysis and Machine Intelligence',
    shortName: 'IEEE TPAMI',
    publisher: 'IEEE',
    category: 'engineering',
    impactFactor: 23.6,
    tier: 'elite',
    issn: '0162-8828',
    openAccess: false,
    description: 'The world\'s leading journal on computer vision, pattern recognition, and machine learning methods.',
    wordLimit: 14,
    wordLimitUnit: 'pages (double-column)',
    abstractLimit: 200,
    referenceStyle: 'ieee',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '4–6 IEEE Taxonomy terms',
    sections: ['Introduction', 'Related Work', 'Proposed Method', 'Experiments', 'Conclusion'],
    submissionGuidelines: [
      'IEEE Transactions format required (LaTeX IEEEtran class)',
      'Double-blind peer review — all identifying info removed',
      'Code and datasets must be submitted for reproducibility check',
      'Minimum 30% improvement over state-of-the-art or fundamental insight required',
      'Ablation studies strongly expected for deep learning papers',
      'Index Terms from IEEE Taxonomy required',
      'Brief Papers available (6 pages) for focused contributions',
    ],
    manuscriptStructure: [
      { section: 'Title',           notes: 'Technical; precise terminology' },
      { section: 'Abstract',       notes: '200 words max; problem, method, results' },
      { section: 'Index Terms',    notes: '4–6 IEEE Taxonomy terms; required' },
      { section: 'Introduction',   notes: 'Problem; motivation; contributions (bulleted list)' },
      { section: 'Related Work',   notes: 'Comprehensive survey; positioning vs. SOTA' },
      { section: 'Proposed Method', notes: 'Full technical description; architecture; algorithms' },
      { section: 'Experiments',    notes: 'Datasets; baselines; ablations; SOTA comparison' },
      { section: 'Conclusion',     notes: 'Summary; limitations; future work' },
      { section: 'References',     notes: 'IEEE format; extensive' },
      { section: 'Appendix',       notes: 'Proofs; additional results' },
    ],
    thesisConversionTips: [
      'IEEE papers require LaTeX with IEEEtran class — convert from Word if needed',
      'List explicit contributions as a bulleted list at the end of Introduction',
      'Related Work is critical at TPAMI — ensure comprehensive literature positioning',
      'Ablation studies are mandatory for deep learning methods',
      'Submit code for reproducibility verification',
      'Double-blind review requires removing all self-identifying references',
    ],
  },
  {
    id: 'nature-energy',
    name: 'Nature Energy',
    publisher: 'Springer Nature',
    category: 'engineering',
    impactFactor: 60.9,
    tier: 'elite',
    issn: '2058-7546',
    openAccess: false,
    description: 'High-impact journal covering all aspects of energy research: generation, storage, transmission, and policy implications.',
    wordLimit: 5000,
    abstractLimit: 150,
    referenceStyle: 'nature',
    maxReferences: 50,
    maxFigures: 8,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
    submissionGuidelines: [
      'Research must address energy challenges with broad significance',
      'Policy and societal implications expected in Discussion',
      'Device performance must include stability data',
      'Efficiency claims must follow standardized measurement protocols',
      'Nature journal group style and guidelines apply',
      'Life-cycle analysis or techno-economic analysis valued',
    ],
    manuscriptStructure: [
      { section: 'Title',         notes: 'Focus on energy breakthrough; 90 chars max' },
      { section: 'Abstract',     notes: '150 words; unstructured; performance metrics included' },
      { section: 'Introduction', notes: 'Energy challenge context; 2–3 paragraphs' },
      { section: 'Results',      notes: 'Device/material performance data' },
      { section: 'Discussion',   notes: 'Broader energy impact; policy/economic angle' },
      { section: 'Methods',      notes: 'After Discussion; fabrication and characterization' },
      { section: 'References',   notes: 'Nature style; ~50' },
    ],
    thesisConversionTips: [
      'Frame device/material results in terms of broader energy transition impact',
      'Include stability, scalability, and reproducibility data — critical for energy research',
      'Add techno-economic or policy analysis if thesis lacks it',
    ],
  },
  {
    id: 'advanced-materials',
    name: 'Advanced Materials',
    publisher: 'Wiley-VCH',
    category: 'engineering',
    impactFactor: 32.1,
    tier: 'elite',
    issn: '0935-9648',
    openAccess: false,
    description: 'Global leader in materials science, covering functional materials, devices, and their applications from nanoscale to macroscale.',
    wordLimit: 5000,
    abstractLimit: 250,
    referenceStyle: 'adv-materials',
    maxReferences: 50,
    maxFigures: 7,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '5',
    sections: ['Introduction', 'Results and Discussion', 'Conclusion', 'Experimental Section'],
    submissionGuidelines: [
      'Research has transformative impact on materials discovery or application',
      'Table of Contents (TOC) entry required: image + 2 sentences',
      'Full Papers (5,000 words), Communications (2,000 words), Reviews accepted',
      'Comprehensive characterization in Supporting Information',
      'Advanced Optical Microscopy images should meet publication quality',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Materials-focused; specific' },
      { section: 'TOC Entry',             notes: 'Image + 2 sentences; required' },
      { section: 'Abstract',             notes: '250 words; highlight key performance metrics' },
      { section: 'Keywords',             notes: '5 terms' },
      { section: 'Introduction',         notes: 'Materials challenge context; prior art' },
      { section: 'Results and Discussion', notes: 'Combined; structure–property–performance' },
      { section: 'Conclusion',           notes: '1–2 paragraphs; outlook' },
      { section: 'Experimental Section', notes: 'After Conclusion; full synthesis and characterization' },
      { section: 'Supporting Information', notes: 'Extensive characterization; raw data' },
      { section: 'References',           notes: 'Adv. Materials style; ~50' },
    ],
    thesisConversionTips: [
      'Create a TOC graphic with a 2-sentence caption highlighting the advance',
      'Structure-property-performance narrative is the heart of an Adv. Materials paper',
      'Combine Results and Discussion — not separated as in some thesis formats',
    ],
  },

  // ─── SOCIAL SCIENCES ─────────────────────────────────────────────────────────
  {
    id: 'ajs',
    name: 'American Journal of Sociology',
    shortName: 'AJS',
    publisher: 'University of Chicago Press',
    category: 'social-sciences',
    impactFactor: 8.3,
    tier: 'elite',
    issn: '0002-9602',
    openAccess: false,
    description: 'The oldest American sociology journal, publishing theoretical and empirical work with broad sociological significance.',
    wordLimit: 14000,
    abstractLimit: 200,
    referenceStyle: 'chicago',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Background/Literature Review', 'Data and Methods', 'Findings', 'Discussion/Conclusion'],
    submissionGuidelines: [
      'Must make a theoretical contribution, not just an empirical one',
      'Chicago author-date citation style required',
      'Manuscripts should be 8,000–14,000 words (including notes and references)',
      'Double-blind review — no identifying information',
      'Notes and References follow main text',
      'Non-sexist, non-racist language policy enforced',
    ],
    manuscriptStructure: [
      { section: 'Title',                     notes: 'Theoretical framing often in title' },
      { section: 'Abstract',                 notes: '200 words; theoretical contribution explicit' },
      { section: 'Introduction',             notes: 'Social problem + theoretical gap + contribution' },
      { section: 'Background / Literature Review', notes: 'Theoretical and empirical positioning' },
      { section: 'Data and Methods',         notes: 'Data sources; analytical strategy' },
      { section: 'Findings',                 notes: 'Tables, figures, or qualitative evidence' },
      { section: 'Discussion and Conclusion', notes: 'Theoretical implications; limitations' },
      { section: 'References',               notes: 'Chicago author-date style' },
      { section: 'Notes',                    notes: 'Endnotes for elaboration' },
    ],
    thesisConversionTips: [
      'AJS requires theoretical framing throughout — strengthen theoretical contribution',
      'Literature Review must be a selective theoretical positioning, not a comprehensive survey',
      'Chicago author-date style: convert from APA/MLA if needed',
      'Sociological jargon must be precise; define key concepts clearly',
      'Word limits are generous; detailed argumentation is valued',
    ],
  },
  {
    id: 'apsr',
    name: 'American Political Science Review',
    shortName: 'APSR',
    publisher: 'Cambridge University Press / APSA',
    category: 'social-sciences',
    impactFactor: 7.9,
    tier: 'elite',
    issn: '0003-0554',
    openAccess: false,
    description: 'The flagship journal of American political science, covering all subfields: comparative politics, IR, political theory, and methodology.',
    wordLimit: 12000,
    abstractLimit: 150,
    referenceStyle: 'apsa',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '4–6',
    sections: ['Introduction', 'Literature Review / Theory', 'Research Design', 'Results', 'Conclusion'],
    submissionGuidelines: [
      'Word limit: 8,000–12,000 words excluding references and appendix',
      'APSA Style Manual citations required',
      'Online Supplementary Appendix for data, code, and robustness checks',
      'Pre-registration statement required for empirical papers',
      'Replication data and code deposited in Harvard Dataverse',
      'Double-blind review',
    ],
    manuscriptStructure: [
      { section: 'Title',                notes: 'Question or claim framing preferred' },
      { section: 'Abstract',            notes: '150 words; question, approach, finding, implication' },
      { section: 'Keywords',            notes: '4–6 terms' },
      { section: 'Introduction',        notes: 'Political question; theory/empirics; contribution; roadmap' },
      { section: 'Theory',              notes: 'Formal or informal; testable hypotheses' },
      { section: 'Research Design',     notes: 'Cases, data, strategy, identification' },
      { section: 'Results',             notes: 'Main findings; tables; figures' },
      { section: 'Conclusion',          notes: 'Contribution; policy implications; limits' },
      { section: 'References',          notes: 'APSA style' },
      { section: 'Online Appendix',     notes: 'Robustness checks; additional analysis' },
    ],
    thesisConversionTips: [
      'APSR expects clear theory with testable hypotheses — extract from thesis theory chapter',
      'Pre-registration is increasingly expected; note if original study lacked pre-registration',
      'Deposit replication data to Harvard Dataverse before submission',
      'Online Appendix allows extensive robustness checks from thesis analysis',
    ],
  },
  {
    id: 'jfe',
    name: 'Journal of Financial Economics',
    shortName: 'JFE',
    publisher: 'Elsevier',
    category: 'social-sciences',
    impactFactor: 8.2,
    tier: 'elite',
    issn: '0304-405X',
    openAccess: false,
    description: 'Leading journal in financial economics covering asset pricing, corporate finance, banking, and market microstructure.',
    wordLimit: null,
    abstractLimit: 150,
    referenceStyle: 'apa7',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '4–6 JEL codes + keywords',
    sections: ['Introduction', 'Hypothesis Development', 'Data', 'Methodology', 'Results', 'Conclusion'],
    submissionGuidelines: [
      'JEL classification codes required',
      'Internet Appendix for additional tables and robustness tests',
      'WRDS, Compustat, CRSP data sources should be fully described',
      'Endogeneity concerns must be addressed',
      'Causal identification strategy required for empirical papers',
      'Econometric rigor expected throughout',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Specific financial claim or question' },
      { section: 'Abstract',              notes: '150 words; question; method; economic significance' },
      { section: 'JEL Codes + Keywords', notes: 'Required classification' },
      { section: 'Introduction',          notes: 'Economic question; related literature; results summary; organization' },
      { section: 'Hypothesis Development', notes: 'Theoretical motivation for empirical tests' },
      { section: 'Data',                  notes: 'Sources; sample selection; summary statistics' },
      { section: 'Methodology',          notes: 'Empirical strategy; identification; endogeneity' },
      { section: 'Results',              notes: 'Main tables; economic magnitude; robustness' },
      { section: 'Conclusion',           notes: 'Contribution; implications; limits' },
      { section: 'References',           notes: 'Author-year format' },
      { section: 'Internet Appendix',   notes: 'Robustness; additional tables' },
    ],
    thesisConversionTips: [
      'JFE Introduction must summarize all key results — finance readers decide from Introduction',
      'Add JEL classification codes (not typical in thesis)',
      'Endogeneity and identification are critical — ensure thesis methodology addresses this',
      'Economic magnitude (not just statistical significance) must be discussed',
      'Convert extensive robustness tables to Internet Appendix',
    ],
  },

  // ─── HUMANITIES ──────────────────────────────────────────────────────────────
  {
    id: 'pmla',
    name: 'PMLA',
    publisher: 'Modern Language Association',
    category: 'humanities',
    impactFactor: 1.4,
    tier: 'elite',
    issn: '0030-8129',
    openAccess: false,
    description: 'Publications of the Modern Language Association — the most prestigious journal in literary and language studies.',
    wordLimit: 9000,
    abstractLimit: 100,
    referenceStyle: 'mla9',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['(Continuous scholarly essay — no formal sections)'],
    submissionGuidelines: [
      'MLA style throughout (9th edition)',
      'Scholarly essay format — no section headers typical',
      'Abstract: 100 words max, submitted separately',
      'Works Cited follows Chicago or MLA format',
      'Double-blind review',
      'Submissions should advance the discipline, not just interpret a single text',
      'Theoretical frameworks must be explicitly engaged',
      'Avoid biographical criticism as primary method',
    ],
    manuscriptStructure: [
      { section: 'Title',         notes: 'Literary and theoretical framing; may include colon' },
      { section: 'Abstract',     notes: '100 words max; argument stated clearly' },
      { section: 'Essay Body',   notes: 'Continuous prose; no formal section headings; 7,000–9,000 words' },
      { section: 'Notes',        notes: 'Endnotes for elaboration; not for citations' },
      { section: 'Works Cited',  notes: 'MLA 9th edition format' },
    ],
    thesisConversionTips: [
      'Literary studies theses must be rewritten as scholarly essays — not chapters',
      'Remove all thesis-specific language ("In Chapter 2 I argued...", "This thesis...")',
      'Compress 5-chapter thesis to a single focused argument (one thesis chapter usually)',
      'MLA 9th edition throughout — update any citations from older editions',
      'Abstract is only 100 words — most concise among academic journals',
      'Engage explicitly with theoretical frameworks fashionable in the field',
    ],
  },
  {
    id: 'ahr',
    name: 'American Historical Review',
    shortName: 'AHR',
    publisher: 'Oxford University Press / AHA',
    category: 'humanities',
    impactFactor: 2.7,
    tier: 'elite',
    issn: '0002-8762',
    openAccess: false,
    description: 'The official journal of the American Historical Association, publishing original historical scholarship across all periods and regions.',
    wordLimit: 10000,
    abstractLimit: 150,
    referenceStyle: 'chicago',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    sections: ['(Continuous historical narrative — no formal sections)'],
    submissionGuidelines: [
      'Chicago notes-bibliography style required (17th edition)',
      'Articles should make a significant original argument',
      'Must engage primary sources; archival research valued',
      'Transnational and comparative perspectives welcomed',
      'Footnotes (not endnotes) for citations and elaboration',
      '9,000–10,000 words including footnotes',
      'Blind peer review',
    ],
    manuscriptStructure: [
      { section: 'Title',       notes: 'Evocative; often includes colon with qualifier' },
      { section: 'Abstract',   notes: '150 words; argument and sources stated' },
      { section: 'Essay Body', notes: 'Continuous narrative; 8,000–9,500 words body' },
      { section: 'Footnotes',  notes: 'Chicago Notes style; substantive notes for argument extension' },
      { section: 'Bibliography', notes: 'Primary and secondary sources separately listed' },
    ],
    thesisConversionTips: [
      'History theses must be compressed to one focused argument',
      'AHR values original archival evidence — foreground your primary source work',
      'Chicago footnote style is standard; endnote-based theses need reformatting',
      'Avoid historiographical surveys that read like literature reviews',
      'The argument must be stated clearly in the first paragraph',
    ],
  },

  // ─── PSYCHOLOGY ──────────────────────────────────────────────────────────────
  {
    id: 'psych-review',
    name: 'Psychological Review',
    publisher: 'American Psychological Association',
    category: 'psychology',
    impactFactor: 10.3,
    tier: 'elite',
    issn: '0033-295X',
    openAccess: false,
    description: 'APA\'s premier theory journal, publishing integrative theoretical contributions and broad reviews that advance psychological science.',
    wordLimit: 16000,
    abstractLimit: 250,
    referenceStyle: 'apa7',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '4–6',
    sections: ['Introduction', 'Theory/Model', 'Evidence Review', 'General Discussion'],
    submissionGuidelines: [
      'Purely empirical papers not accepted — must advance theory',
      'APA 7th edition format required throughout',
      'May present new theories, revise existing ones, or integrate fields',
      'Mathematical models and computational approaches welcomed',
      'No length limits — comprehensiveness valued',
      'Pre-registration not required but welcomed',
    ],
    manuscriptStructure: [
      { section: 'Title',              notes: 'Theoretical focus explicit' },
      { section: 'Abstract',          notes: '250 words; theory stated and contribution clear' },
      { section: 'Keywords',          notes: '4–6 APA taxonomy terms' },
      { section: 'Introduction',      notes: 'Theoretical problem and review scope' },
      { section: 'Theory / Model',    notes: 'Core theoretical contribution' },
      { section: 'Evidence Review',   notes: 'Empirical and theoretical support' },
      { section: 'General Discussion', notes: 'Implications; predictions; limitations' },
      { section: 'References',        notes: 'APA 7th; extensive' },
    ],
    thesisConversionTips: [
      'Psychology theses that are purely empirical need a theoretical contribution for Psych Review',
      'APA 7th edition formatting throughout — running head, page numbers, bias-free language',
      'Identify the theoretical advance your thesis makes and build the manuscript around it',
    ],
  },
  {
    id: 'jpsp',
    name: 'Journal of Personality and Social Psychology',
    shortName: 'JPSP',
    publisher: 'American Psychological Association',
    category: 'psychology',
    impactFactor: 7.3,
    tier: 'elite',
    issn: '0022-3514',
    openAccess: false,
    description: 'Leading empirical journal in social and personality psychology, covering attitudes, social cognition, emotion, and individual differences.',
    wordLimit: 10000,
    abstractLimit: 250,
    referenceStyle: 'apa7',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'structured',
    abstractSections: ['Objective', 'Method', 'Results', 'Conclusions'],
    keywordsRequired: true,
    keywordsCount: '4–6',
    sections: ['Introduction', 'Study 1 Method', 'Study 1 Results', '...multiple studies...', 'General Discussion'],
    submissionGuidelines: [
      'APA 7th edition required throughout',
      'Replications and multi-study packages preferred',
      'Pre-registration strongly encouraged; report on OSF',
      'Effect sizes (Cohen\'s d, η², etc.) required in all results',
      'Open materials and open data badges available',
      'Power analysis and justification of sample sizes required',
      'CONSORT or PRISMA equivalents for meta-analyses',
    ],
    manuscriptStructure: [
      { section: 'Title',                notes: 'Psychological construct + DV or question' },
      { section: 'Abstract',            notes: 'Structured; 4 sections; 250 words' },
      { section: 'Keywords',            notes: '4–6 terms' },
      { section: 'Introduction',        notes: 'Theory; gap; hypotheses; study overview' },
      { section: 'Study N: Method',     notes: 'Participants; design; measures; procedure' },
      { section: 'Study N: Results',    notes: 'Effect sizes; CIs; all pre-registered tests' },
      { section: 'General Discussion',  notes: 'Integrate across studies; theory implications; limits' },
      { section: 'References',          notes: 'APA 7th' },
      { section: 'Supplemental Materials', notes: 'Measures; additional analyses' },
    ],
    thesisConversionTips: [
      'Multi-study thesis chapters convert well to JPSP format',
      'APA 7th edition required — update from older APA versions',
      'Pre-registration is expected; acknowledge if studies were not pre-registered',
      'Report effect sizes in every result — Cohen\'s d, partial η², etc.',
      'Include open data and open materials statements',
      'Power analysis for each study sample size must be included',
    ],
  },
  {
    id: 'psych-science',
    name: 'Psychological Science',
    publisher: 'SAGE / APS',
    category: 'psychology',
    impactFactor: 6.9,
    tier: 'high',
    issn: '0956-7976',
    openAccess: false,
    description: 'Flagship journal of the Association for Psychological Science, publishing cutting-edge empirical research across all areas of psychology.',
    wordLimit: 4000,
    abstractLimit: 150,
    referenceStyle: 'apa7',
    maxReferences: null,
    maxFigures: 4,
    maxTables: 2,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '5',
    sections: ['Introduction', 'Method', 'Results', 'Discussion'],
    submissionGuidelines: [
      'Shorter format preferred (≤4,000 words)',
      'Pre-registration required for confirmatory studies',
      'Open practices badges strongly encouraged',
      'APA 7th edition style throughout',
      'Effect sizes and confidence intervals required',
      'Transparency and Openness Promotion (TOP) guidelines apply',
    ],
    manuscriptStructure: [
      { section: 'Title',       notes: 'Concise; accessible to broad audience' },
      { section: 'Abstract',   notes: '150 words; main finding prominent' },
      { section: 'Keywords',   notes: '5 terms' },
      { section: 'Introduction', notes: '500–800 words; theory + hypotheses' },
      { section: 'Method',     notes: 'Participants; design; materials; procedure' },
      { section: 'Results',    notes: 'Effect sizes; CIs; pre-registered tests' },
      { section: 'Discussion', notes: '500–800 words; implications; limits' },
      { section: 'References', notes: 'APA 7th' },
    ],
    thesisConversionTips: [
      'Psych Science prefers short papers — select 1 study from thesis, not all',
      'Most thesis chapters exceed 4,000 words significantly — heavy cutting required',
      'Ensure pre-registration compliance; note lack of pre-registration transparently',
      'Open materials and data sharing required for badges',
    ],
  },

  // ─── COMPUTER SCIENCE ────────────────────────────────────────────────────────
  {
    id: 'jacm',
    name: 'Journal of the ACM',
    shortName: 'JACM',
    publisher: 'ACM',
    category: 'computer-science',
    impactFactor: 7.5,
    tier: 'elite',
    issn: '0004-5411',
    openAccess: false,
    description: 'Flagship journal of the ACM, publishing highest-quality theoretical computer science and algorithmics research.',
    wordLimit: null,
    abstractLimit: 250,
    referenceStyle: 'acm',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: 'ACM CCS concepts',
    sections: ['Introduction', 'Preliminaries', 'Main Results', 'Analysis / Proofs', 'Conclusion'],
    submissionGuidelines: [
      'ACM LaTeX template required (acmart class)',
      'ACM Computing Classification System (CCS) concepts required',
      'Proofs may be included in appendix or supplementary material',
      'No length limits for full journal articles',
      'ACM Open Access options available',
      'Algorithm pseudocode using Algorithm2e or similar package',
    ],
    manuscriptStructure: [
      { section: 'Title',           notes: 'Theoretical result or problem framing' },
      { section: 'Abstract',       notes: '250 words; main result stated precisely' },
      { section: 'CCS Concepts',   notes: 'ACM CCS taxonomy tags; required' },
      { section: 'Keywords',       notes: 'Additional keywords' },
      { section: 'Introduction',   notes: 'Problem; prior work; contributions; paper structure' },
      { section: 'Preliminaries',  notes: 'Definitions; notation; background lemmas' },
      { section: 'Main Results',   notes: 'Theorems; algorithms; constructions' },
      { section: 'Analysis',       notes: 'Proofs; complexity analysis; correctness' },
      { section: 'Conclusion',     notes: 'Open problems; future directions' },
      { section: 'References',     notes: 'ACM format' },
      { section: 'Appendix',       notes: 'Omitted proofs; extended results' },
    ],
    thesisConversionTips: [
      'CS theory theses convert well to JACM — length is not constrained',
      'Use ACM LaTeX template (acmart) from the start',
      'Add ACM CCS concept tags — not typical in thesis format',
      'Structure as Preliminaries → Main Results → Analysis rather than thesis chapters',
      'Move secondary proofs and lemmas to Appendix',
    ],
  },
  {
    id: 'jmlr',
    name: 'Journal of Machine Learning Research',
    shortName: 'JMLR',
    publisher: 'MIT Press / JMLR Inc.',
    category: 'computer-science',
    impactFactor: 6.0,
    tier: 'high',
    issn: '1532-4435',
    openAccess: true,
    description: 'Open-access journal publishing high-quality research on all aspects of machine learning, from theory to applications.',
    wordLimit: null,
    abstractLimit: 200,
    referenceStyle: 'jmlr',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '4–8',
    sections: ['Introduction', 'Related Work', 'Method / Model', 'Experiments / Theory', 'Conclusion'],
    submissionGuidelines: [
      'LaTeX submission required; JMLR style file available',
      'No length limits — comprehensive papers welcomed',
      'Fully open access; no APC (no charge to authors)',
      'Action Editor process; 8-week target review',
      'Code and data availability encouraged',
      'Reproducibility strongly valued',
    ],
    manuscriptStructure: [
      { section: 'Title',          notes: 'ML-specific; method or theorem name acceptable' },
      { section: 'Abstract',      notes: '200 words; method + key results' },
      { section: 'Keywords',      notes: '4–8 ML terms' },
      { section: 'Introduction',  notes: 'Problem; motivation; contributions' },
      { section: 'Related Work',  notes: 'Comprehensive literature comparison' },
      { section: 'Method / Model', notes: 'Full technical description; theoretical analysis' },
      { section: 'Experiments',   notes: 'Benchmarks; ablations; baselines' },
      { section: 'Conclusion',    notes: 'Summary; limitations; future work' },
      { section: 'References',    notes: 'JMLR format' },
      { section: 'Appendix',      notes: 'Proofs; additional experiments' },
    ],
    thesisConversionTips: [
      'JMLR is ideal for ML theses — no length limit and open access',
      'Use JMLR LaTeX style file for formatting',
      'JMLR is free to publish — excellent choice for PhD thesis conversion',
      'Include theoretical guarantees if your work has them',
      'Comprehensive experiment section from thesis is a competitive advantage',
    ],
  },

  // ─── INTERDISCIPLINARY ───────────────────────────────────────────────────────
  {
    id: 'pnas',
    name: 'Proceedings of the National Academy of Sciences',
    shortName: 'PNAS',
    publisher: 'National Academy of Sciences',
    category: 'interdisciplinary',
    impactFactor: 12.8,
    tier: 'elite',
    issn: '0027-8424',
    openAccess: false,
    description: 'Multidisciplinary journal of the NAS, publishing significant research across biological, physical, social, and behavioral sciences.',
    wordLimit: 6000,
    abstractLimit: 250,
    referenceStyle: 'pnas',
    maxReferences: 40,
    maxFigures: 6,
    maxTables: 4,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '5',
    sections: ['Introduction', 'Results', 'Discussion', 'Materials and Methods'],
    submissionGuidelines: [
      'Significance Statement required: 120 words, plain language, for public audience',
      'Must demonstrate significance beyond single discipline',
      'Track I: NAS member-sponsored; Track II: direct submission',
      'PNAS format: PNAS LaTeX template or MS Word template',
      'Data deposition required for biological sequence data',
      'Open data sharing policy applies',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Broad significance clear in title' },
      { section: 'Abstract',              notes: '250 words; multidisciplinary audience' },
      { section: 'Significance Statement', notes: '120 words max; plain language; required' },
      { section: 'Keywords',              notes: '5 terms' },
      { section: 'Introduction',          notes: 'Background; gap; approach; 3–5 paragraphs' },
      { section: 'Results',              notes: 'Main data; subheadings' },
      { section: 'Discussion',           notes: 'Cross-disciplinary interpretation' },
      { section: 'Materials and Methods', notes: 'Full detail at end' },
      { section: 'References',           notes: 'PNAS style; numbered; ~40' },
      { section: 'SI Appendix',          notes: 'Supplemental information; additional figures' },
    ],
    thesisConversionTips: [
      'Write a Significance Statement (120 words) — unique PNAS requirement for lay audiences',
      'Frame thesis findings to demonstrate cross-disciplinary significance',
      'Materials and Methods go after Discussion — different from many journals',
      'PNAS is an excellent target for interdisciplinary thesis work',
      'Consider PNAS Direct Submission track to avoid needing NAS member sponsorship',
    ],
  },
  {
    id: 'nature-comms',
    name: 'Nature Communications',
    publisher: 'Springer Nature',
    category: 'interdisciplinary',
    impactFactor: 16.6,
    tier: 'high',
    issn: '2041-1723',
    openAccess: true,
    description: 'Open-access journal covering all areas of the natural sciences, offering rigorous peer review with Nature-group standards at a broader scope.',
    wordLimit: 5000,
    abstractLimit: 150,
    referenceStyle: 'nature',
    maxReferences: 50,
    maxFigures: 10,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
    submissionGuidelines: [
      'Nature-group guidelines apply; Reporting Summary required',
      'Open access with APC',
      'No scope restrictions — all natural science disciplines',
      'Data availability statement required',
      'Peer Review File published with accepted papers',
      'Article Processing Charge applies (~€2,990 as of 2024)',
    ],
    manuscriptStructure: [
      { section: 'Title',               notes: 'Specific finding; max 90 characters' },
      { section: 'Abstract',           notes: '150 words max; unstructured' },
      { section: 'Introduction',       notes: '3–5 paragraphs; significance and gap' },
      { section: 'Results',            notes: 'Main data with subheadings' },
      { section: 'Discussion',         notes: 'Implications; limitations; future directions' },
      { section: 'Methods',           notes: 'After Discussion; full detail' },
      { section: 'Data Availability', notes: 'Required; repository links' },
      { section: 'References',        notes: 'Nature style; ~50' },
      { section: 'Reporting Summary', notes: 'Nature Research required form' },
    ],
    thesisConversionTips: [
      'Nature Communications is an excellent first target for thesis conversion — broad scope, high prestige',
      'Complete the Nature Reporting Summary — mandatory for all submissions',
      'Data must be deposited in a public repository before submission',
      'OA fee applies — check if institution has transformative agreement',
      'Less restrictive on significance than Nature itself — strong but not extraordinary results acceptable',
    ],
  },

  // ─── OPEN ACCESS ─────────────────────────────────────────────────────────────
  {
    id: 'plos-one',
    name: 'PLOS ONE',
    publisher: 'PLOS',
    category: 'open-access',
    impactFactor: 3.7,
    tier: 'moderate',
    issn: '1932-6203',
    openAccess: true,
    description: 'The world\'s largest multidisciplinary open-access journal, publishing technically sound research in all areas of science and medicine.',
    wordLimit: null,
    abstractLimit: 300,
    referenceStyle: 'vancouver',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'structured',
    abstractSections: ['Background', 'Methodology/Principal Findings', 'Conclusions/Significance'],
    keywordsRequired: false,
    sections: ['Introduction', 'Materials and Methods', 'Results', 'Discussion'],
    submissionGuidelines: [
      'Technical soundness is the criterion — novelty or impact NOT required',
      'IMRAD format (Introduction, Methods, Results, Discussion)',
      'Data availability required; publicly archived datasets',
      'Reporting guidelines (CONSORT, STROBE, ARRIVE, etc.) mandatory',
      'APC (~$1,695 USD as of 2024)',
      'Methods section BEFORE Results — critical PLOS ONE format requirement',
      'Author contributions required (CRediT taxonomy)',
    ],
    manuscriptStructure: [
      { section: 'Title',                  notes: 'Specific; informative; no jargon' },
      { section: 'Abstract',              notes: 'Structured; 3 sections; 300 words max' },
      { section: 'Introduction',          notes: 'Background; gap; aims' },
      { section: 'Materials and Methods', notes: 'Before Results; full detail; ethics statement' },
      { section: 'Results',              notes: 'Data presentation; no interpretation' },
      { section: 'Discussion',           notes: 'Interpretation; limitations; future directions' },
      { section: 'References',           notes: 'Vancouver; numbered; no limit' },
      { section: 'Author Contributions', notes: 'CRediT taxonomy; required' },
      { section: 'Data Availability Statement', notes: 'Required; specific repository' },
    ],
    thesisConversionTips: [
      'PLOS ONE is ideal for first-time publishers converting a thesis chapter',
      'No novelty requirement — technically sound work will be accepted',
      'Methods must appear BEFORE Results (different from many journals)',
      'Ethics statement must be in Methods section explicitly',
      'Attach your full dataset to a public repository (Zenodo, Dryad, OSF)',
      'All figures must be uploaded as separate files with captions in text',
    ],
  },
  {
    id: 'scientific-reports',
    name: 'Scientific Reports',
    publisher: 'Springer Nature',
    category: 'open-access',
    impactFactor: 4.6,
    tier: 'moderate',
    issn: '2045-2322',
    openAccess: true,
    description: 'Springer Nature\'s open-access journal accepting technically valid research across all areas of natural and clinical sciences.',
    wordLimit: null,
    abstractLimit: 200,
    referenceStyle: 'nature',
    maxReferences: null,
    maxFigures: null,
    maxTables: null,
    abstractStructure: 'unstructured',
    keywordsRequired: false,
    sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
    submissionGuidelines: [
      'Technically sound research published regardless of novelty/impact',
      'Nature-group Reporting Summary may be required for life sciences',
      'Data availability statement required',
      'APC (~€1,690 as of 2024); institutional waivers available',
      'Methods after Discussion (Nature format)',
      'Open peer review available as option',
    ],
    manuscriptStructure: [
      { section: 'Title',             notes: 'Informative; specific to finding' },
      { section: 'Abstract',         notes: '200 words max; unstructured' },
      { section: 'Introduction',     notes: 'Background; aims; 3–5 paragraphs' },
      { section: 'Results',          notes: 'Data with subheadings' },
      { section: 'Discussion',       notes: 'Interpretation; limitations' },
      { section: 'Methods',         notes: 'After Discussion; full detail' },
      { section: 'References',      notes: 'Nature style' },
      { section: 'Data Availability', notes: 'Required statement' },
    ],
    thesisConversionTips: [
      'Scientific Reports is a safe, reputable target for solid thesis work without breakthrough novelty',
      'Nature-family formatting applies — Methods after Discussion',
      'No word or figure limits — full thesis chapter detail can be included',
      'Check institutional transformative agreement with Springer Nature to waive APC',
    ],
  },
  {
    id: 'frontiers',
    name: 'Frontiers in [Subject]',
    publisher: 'Frontiers Media',
    category: 'open-access',
    impactFactor: 5.2,
    tier: 'moderate',
    issn: 'varies',
    openAccess: true,
    description: 'A family of open-access journals covering all academic disciplines with a focus on rigorous specialty research and open science principles.',
    wordLimit: null,
    abstractLimit: 350,
    referenceStyle: 'frontiers',
    maxReferences: null,
    maxFigures: 15,
    maxTables: 15,
    abstractStructure: 'unstructured',
    keywordsRequired: true,
    keywordsCount: '5–8',
    sections: ['Introduction', 'Materials and Methods', 'Results', 'Discussion', 'Conclusion'],
    submissionGuidelines: [
      'Over 200 specialty journals — select most relevant journal AND specialty section',
      'Collaborative peer review: authors can interact with reviewers',
      'Tiered article types: Original Research, Review, Mini Review, Perspective',
      'Open data policy; raw data upload encouraged',
      'APC charged per article (~€950–2,590 depending on journal)',
      'Author Guidelines page for specific specialty section requirements',
      'Separate Conclusion section distinct from Discussion',
    ],
    manuscriptStructure: [
      { section: 'Title',                   notes: 'Specific; specialty field terminology' },
      { section: 'Abstract',               notes: '350 words max; unstructured' },
      { section: 'Keywords',               notes: '5–8 terms; taxonomy specific to specialty' },
      { section: 'Introduction',           notes: 'Background; rationale; aims' },
      { section: 'Materials and Methods',  notes: 'Before Results; full detail' },
      { section: 'Results',               notes: 'Data; figures; tables' },
      { section: 'Discussion',            notes: 'Interpretation; contextualization' },
      { section: 'Conclusion',            notes: 'Separate section; explicit summary + outlook' },
      { section: 'Data Availability Statement', notes: 'Required' },
      { section: 'References',            notes: 'Frontiers bibliography style' },
      { section: 'Author Contributions',  notes: 'CRediT taxonomy' },
    ],
    thesisConversionTips: [
      'Choose the most specific Frontiers specialty section for best fit',
      'Frontiers requires a separate Conclusion section — split from Discussion',
      'Collaborative review model allows responding to reviewers directly during review',
      'Broad word limits make thesis-to-manuscript conversion straightforward',
      'Check institutional agreements for APC discounts',
    ],
  },
];

// ─── THESIS STRUCTURE TEMPLATES ─────────────────────────────────────────────
const THESIS_SECTIONS = {
  stem: [
    { id: 'title', label: 'Title Page', required: true },
    { id: 'abstract', label: 'Abstract', required: true },
    { id: 'acknowledgments', label: 'Acknowledgments', required: false },
    { id: 'toc', label: 'Table of Contents', required: false },
    { id: 'intro', label: 'Introduction / Chapter 1', required: true },
    { id: 'literature', label: 'Literature Review / Chapter 2', required: true },
    { id: 'methods', label: 'Materials & Methods / Chapter 3', required: true },
    { id: 'results', label: 'Results / Chapter 4', required: true },
    { id: 'discussion', label: 'Discussion / Chapter 5', required: true },
    { id: 'conclusion', label: 'Conclusion / Chapter 6', required: true },
    { id: 'references', label: 'References / Bibliography', required: true },
    { id: 'appendices', label: 'Appendices', required: false },
  ],
  humanities: [
    { id: 'title', label: 'Title Page', required: true },
    { id: 'abstract', label: 'Abstract', required: true },
    { id: 'acknowledgments', label: 'Acknowledgments', required: false },
    { id: 'intro', label: 'Introduction', required: true },
    { id: 'chapter2', label: 'Chapter 2', required: true },
    { id: 'chapter3', label: 'Chapter 3', required: true },
    { id: 'chapter4', label: 'Chapter 4', required: false },
    { id: 'chapter5', label: 'Chapter 5', required: false },
    { id: 'conclusion', label: 'Conclusion', required: true },
    { id: 'bibliography', label: 'Bibliography', required: true },
    { id: 'appendices', label: 'Appendices', required: false },
  ],
  social: [
    { id: 'title', label: 'Title Page', required: true },
    { id: 'abstract', label: 'Abstract', required: true },
    { id: 'intro', label: 'Introduction', required: true },
    { id: 'literature', label: 'Literature Review', required: true },
    { id: 'theory', label: 'Theoretical Framework', required: true },
    { id: 'methods', label: 'Research Methodology', required: true },
    { id: 'findings', label: 'Findings / Results', required: true },
    { id: 'discussion', label: 'Discussion', required: true },
    { id: 'conclusion', label: 'Conclusion', required: true },
    { id: 'references', label: 'References', required: true },
    { id: 'appendices', label: 'Appendices', required: false },
  ],
};

// Export for use in app.js
if (typeof module !== 'undefined') {
  module.exports = { JOURNALS, JOURNAL_CATEGORIES, THESIS_SECTIONS, REFERENCE_STYLES };
}
